openapi: "3.0.0"
info:
  title: "A getting started API"
  version: "1.0.0"
servers:
  - url: /api/v1
  - url: /v1
paths: {}
components:
  schemas:
    User:
      required: ["name"]
      type: "object"
      properties:
        id:
          type: "string"
          description: "The user's unique identifier"
        name:
          type: "string"
          description: "The user's preferred name"
        email:
          type: "string"
          description: "Email address"